services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: microblog_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432" 

  app:
    build: .
    ports:
      - "8000:8000" 
    environment:
      DATABASE_URL: "postgresql://postgres:mysecretpassword@db:5432/microblog_db"
    env_file:
      - .env 
    depends_on:
      - db
